# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e0CvFjupC37s6GyF_qL-s5Z7dcI_C2TU
"""

import math

def calcular_f(n):
    if n == 1:
        return 2
    else:
        return 2 * calcular_f(n - 1) + n**2

# Entrada do usuário
n = int(input("Digite o valor de n (tente números pequenos como 2, 5 ou 10): "))

# Execução da recursão
resultado_recursivo = calcular_f(n)

# Execução da verificação
resultado_verificacao = 6.5 * math.pow(2, n) - (n**2 + 4*n + 6)

print(f"\n--- Resultados para n = {n} ---")
print(f"Recursão: {resultado_recursivo}")
print(f"Fórmula:  {int(resultado_verificacao)}")